# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import gwapit.quickstart.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(gwapit.quickstart.models.Fighter, models.Model),
        ),
        migrations.CreateModel(
            name='Zombie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(gwapit.quickstart.models.Fighter, models.Model),
        ),
    ]
