# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.URLField()),
                ('life', models.PositiveIntegerField(default=100)),
                ('attack', models.PositiveIntegerField(default=5)),
                ('defense', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zombie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.URLField()),
                ('life', models.PositiveIntegerField(default=100)),
                ('attack', models.PositiveIntegerField(default=5)),
                ('defense', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
