# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='cuteness_level',
            field=models.PositiveSmallIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zombie',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zombie',
            name='rot_level',
            field=models.PositiveSmallIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='attack',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='defense',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='life',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='zombie',
            name='attack',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='zombie',
            name='defense',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='zombie',
            name='life',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
